feat(serialize): add Serialize
josh-development/serialize pull request #1
Opened 2022-01-26 03:23 UTC by RealShadowNova

- Format raw data into json compatible data.
- Parse json compatible data into raw data.
- Complete tests for `Serialize`

This PR needs a squash before merge.

2022-01-26 07:33 UTC, dan-online approved these changes
LGTM

2022-01-28 08:15 UTC, eslachance requested changes

2022-01-28 08:15 UTC, eslachance commented on src/lib/Serialize.ts
> +    if (Array.isArray(this.raw)) this.json = { type: Serialize.Type.Array, value: this.formatArray(this.raw) };
4 nearly identical functions, processing the same type of data, where the only difference is where that data ends up. It feels very much like all the formatting itself could be one function called by all 4 of these, which would then only have to put its value where it belongs.

2022-01-28 08:15 UTC, eslachance commented on src/lib/Serialize.ts
> +
What if the value isn't any of the recognized formats? We should throw an error rather than silently ignoring it.

2022-01-28 08:15 UTC, eslachance commented on src/lib/Serialize.ts
> +        case Serialize.Type.Array:
Same as my first comment above : we have 4 different parse functions doing exactly the same thing except where the value ends up, this can be refactored to prevent code duplication.

2022-01-28 08:15 UTC, eslachance commented on src/lib/functions/isObject.ts
> +  return typeof value === 'object' && value ? value.constructor === Object : false;
Using optional chaining, can be simplified: 
`return typeof value === 'object' && value?.constructor === Object;`

2022-01-28 18:58 UTC, RealShadowNova commented on src/lib/Serialize.ts
> +    if (Array.isArray(this.raw)) this.json = { type: Serialize.Type.Array, value: this.formatArray(this.raw) };
How do you want me to do this recursively? Each sub-method calls each other and themselves. Also `format()` sets `this.raw` and it isn't apparent how I could do this recursively quite simply.

2022-01-28 18:58 UTC, RealShadowNova commented on src/lib/Serialize.ts
> +        case Serialize.Type.Array:
Same as my first comment.

2022-01-30 22:02 UTC, eslachance requested changes

2022-01-30 22:06 UTC, RealShadowNova commented on src/lib/Serialize.ts
> +    if (Array.isArray(this.raw)) this.json = { type: Serialize.Type.Array, value: this.formatArray(this.raw) };
Why would this be necessary? All these methods are `private` anyways. The only method that you call publicly is `toJSON()` and `toRaw()`.

2022-01-31 17:25 UTC, RealShadowNova commented on src/lib/Serialize.ts
> +    if (Array.isArray(this.raw)) this.json = { type: Serialize.Type.Array, value: this.formatArray(this.raw) };
To add onto this, if you really want me to, I can make `format()` and `parse()` return the data instead and in `toRaw()` and `toJSON()` to set `this.raw` or `this.json`.

I think this would be a proper solution to your comment.

2022-02-01 13:45 UTC, eslachance approved these changes

2022-02-01 17:25 UTC, merged